### PR TITLE
Cleanup + non-G002

### PR DESCRIPTION
**Pull request by lburgey**
Cleaned up a lot of stuff.

In addition added support for non-G002 entitlements.

### CODE REVIEW

**Comment by lburgey** [comment]
If this is accepted we could publish the docs to e.g. readthedocs.

**Comment by marcvs** [comment]
tox has problems on my host: p36 unavailable, py27 cannot install 'ipaddr' strange

**Comment by lburgey** [comment]
Is your tox up-to-date? I don't have issues.
Python 3.6 is still installed on your end? Maybe you inadvertently upgraded to 3.7 completely

**Comment by marcvs** [comment]
py36 is gone from my system. 
Goodbye py36, hello py38 :)

**Pull request merged**
